/*
 * File: app/view/MyModelsViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ViewOverviewExtJS.view.MyModelsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.mymodels',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        myModels: {
            model: 'ViewOverviewExtJS.model.MyModel',
            data: [
                {
                    id: 1,
                    myField: 'in'
                },
                {
                    id: 2,
                    myField: 'eveniet'
                },
                {
                    id: 3,
                    myField: 'quis'
                },
                {
                    id: 4,
                    myField: 'velit'
                },
                {
                    id: 5,
                    myField: 'beatae'
                },
                {
                    id: 6,
                    myField: 'consequatur'
                },
                {
                    id: 7,
                    myField: 'fugit'
                },
                {
                    id: 8,
                    myField: 'qui'
                },
                {
                    id: 9,
                    myField: 'cumque'
                },
                {
                    id: 10,
                    myField: 'est'
                },
                {
                    id: 11,
                    myField: 'officiis'
                },
                {
                    id: 12,
                    myField: 'optio'
                },
                {
                    id: 13,
                    myField: 'voluptatem'
                },
                {
                    id: 14,
                    myField: 'est'
                },
                {
                    id: 15,
                    myField: 'ut'
                },
                {
                    id: 16,
                    myField: 'harum'
                },
                {
                    id: 17,
                    myField: 'cupiditate'
                },
                {
                    id: 18,
                    myField: 'amet'
                },
                {
                    id: 19,
                    myField: 'ipsum'
                },
                {
                    id: 20,
                    myField: 'eum'
                },
                {
                    id: 21,
                    myField: 'est'
                },
                {
                    id: 22,
                    myField: 'quas'
                },
                {
                    id: 23,
                    myField: 'at'
                },
                {
                    id: 24,
                    myField: 'officia'
                },
                {
                    id: 25,
                    myField: 'sed'
                },
                {
                    id: 26,
                    myField: 'sit'
                },
                {
                    id: 27,
                    myField: 'occaecati'
                },
                {
                    id: 28,
                    myField: 'molestias'
                },
                {
                    id: 29,
                    myField: 'quis'
                },
                {
                    id: 30,
                    myField: 'quis'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});