/*
 * File: app/view/panel/FlipRotatePanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.panel.FlipRotatePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panel.fliprotatepanel',

    requires: [
        'RolandKioskPrint.view.panel.FlipRotatePanelViewModel',
        'RolandKioskPrint.view.panel.FlipRotatePanelViewController',
        'RolandKioskPrint.view.button.PanelButton',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    config: {
        localized: {
            title: 'label.designer.flipRotateTitle'
        }
    },

    controller: 'panel.fliprotatepanel',
    viewModel: {
        type: 'panel.fliprotatepanel'
    },
    cls: 'action-panel',
    width: 120,
    title: 'FLIP / ROTATE',
    titleAlign: 'center',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'panel',
            header: false,
            items: [
                {
                    xtype: 'button.panelbutton',
                    cls: 'icomoon icon-flip-vertical first-column',
                    itemId: 'btnFlipHorizontal',
                    listeners: {
                        click: 'onFlipHorizontalButtonClick'
                    }
                },
                {
                    xtype: 'button.panelbutton',
                    cls: 'icomoon icon-flip-horizontal',
                    itemId: 'btnFlipVertical',
                    listeners: {
                        click: 'onFlipVerticalButtonClick'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            header: false,
            items: [
                {
                    xtype: 'button.panelbutton',
                    cls: 'fa-rotate-right first-column',
                    itemId: 'btnRotateClockwise',
                    listeners: {
                        click: 'onRotateClockwiseButtonClick'
                    }
                },
                {
                    xtype: 'button.panelbutton',
                    cls: 'fa-rotate-left',
                    itemId: 'btnRotateCounterClockwise',
                    listeners: {
                        click: 'onRotateCounterClockwiseButtonClick'
                    }
                }
            ]
        }
    ]

})
