/*
 * File: app/view/panel/GapAdjustmentPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.panel.GapAdjustmentPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panel.gapadjustmentpanel',

    requires: [
        'RolandKioskPrint.view.panel.GapAdjustmentPanelViewModel',
        'RolandKioskPrint.view.panel.GapAdjustmentPanelViewController',
        'RolandKioskPrint.view.button.PanelButton',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    config: {
        localized: {
            title: 'label.designer.gapPanelTitle'
        }
    },

    controller: 'panel.gapadjustmentpanel',
    viewModel: {
        type: 'panel.gapadjustmentpanel'
    },
    cls: 'action-panel',
    width: 120,
    title: 'GAP',
    titleAlign: 'center',

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'panel',
            header: false,
            items: [
                {
                    xtype: 'button.panelbutton',
                    cls: 'icomoon icon-align-horizontal-gap first-column',
                    height: 36,
                    itemId: 'btnXGapAlign',
                    listeners: {
                        click: 'onBtnXGapAlignClick'
                    }
                },
                {
                    xtype: 'button.panelbutton',
                    cls: 'icomoon icon-align-vertical-gap ',
                    height: 36,
                    itemId: 'btnYGapAlign',
                    listeners: {
                        click: 'onBtnYGapAlignClick'
                    }
                }
            ]
        }
    ]

})
