/*
 * File: app/view/panel/ImageOutlinePanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.panel.ImageOutlinePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panel.imageoutlinepanel',

    requires: [
        'RolandKioskPrint.view.panel.ImageOutlinePanelViewModel',
        'RolandKioskPrint.view.panel.ImageOutlinePanelViewController',
        'RolandKioskPrint.view.button.CommandButton',
        'RolandKioskPrint.view.button.ActionButton',
        'Ext.panel.Panel',
        'Ext.form.field.Checkbox',
        'Ext.form.Label',
        'Ext.slider.Single',
        'Ext.button.Button'
    ],

    controller: 'panel.imageoutlinepanel',
    viewModel: {
        type: 'panel.imageoutlinepanel'
    },
    height: 430,
    width: 750,
    layout: 'hbox',
    header: false,

    items: [
        {
            xtype: 'panel',
            margin: '0 0 0 20',
            header: false,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'component',
                    height: 346,
                    html: '<canvas />',
                    itemId: 'canvasContainer',
                    style: 'border: 1px solid #7F7F7F
',
                    width: 470
                },
                {
                    xtype: 'panel',
                    margin: '10 0 0 0',
                    layout: 'hbox',
                    header: false,
                    items: [
                        {
                            xtype: 'checkboxfield',
                            localized: {
                                boxLabel: 'label.designer.viewImage'
                            },
                            cls: 'image-outline-checkbox',
                            itemId: 'chkViewImage',
                            boxLabel: 'SHOW IMAGE',
                            checked: true,
                            bind: {
                                disabled: '{!chkExtractOutline.checked}'
                            },
                            listeners: {
                                change: 'onViewImageCheckboxChange'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            localized: {
                                boxLabel: 'label.designer.viewOutline'
                            },
                            cls: 'image-outline-checkbox',
                            itemId: 'chkViewOutline',
                            margin: '0 0 0 20',
                            boxLabel: 'SHOW OUTLINE',
                            bind: {
                                disabled: '{!chkExtractOutline.checked}'
                            },
                            listeners: {
                                change: 'onViewOutlineCheckboxChange'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onCanvasPanelAfterRender'
            }
        },
        {
            xtype: 'panel',
            flex: 0.35,
            margin: '0 20 0 25',
            header: false,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    bodyStyle: 'border-width: 1px 1px 1px 1px !important
',
                    header: false,
                    items: [
                        {
                            xtype: 'panel',
                            padding: 10,
                            header: false,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    localized: {
                                        text: 'label.designer.brightnessLabel'
                                    },
                                    cls: 'image-outline-label',
                                    text: 'BRIGHTNESS',
                                    bind: {
                                        disabled: '{chkExtractOutline.checked}'
                                    }
                                },
                                {
                                    xtype: 'slider',
                                    cls: 'image-outline-sliders',
                                    itemId: 'brightnessSlider',
                                    value: -24,
                                    maxValue: 50,
                                    minValue: -50,
                                    bind: {
                                        disabled: '{chkExtractOutline.checked}'
                                    },
                                    listeners: {
                                        change: 'onBrightnessSliderChange'
                                    }
                                },
                                {
                                    xtype: 'label',
                                    localized: {
                                        text: 'label.designer.contrastLabel'
                                    },
                                    cls: 'image-outline-label',
                                    text: 'CONTRAST',
                                    bind: {
                                        disabled: '{chkExtractOutline.checked}'
                                    }
                                },
                                {
                                    xtype: 'slider',
                                    cls: 'image-outline-sliders',
                                    itemId: 'contrastSlider',
                                    value: 1,
                                    maxValue: 50,
                                    minValue: -50,
                                    bind: {
                                        disabled: '{chkExtractOutline.checked}'
                                    },
                                    listeners: {
                                        change: 'onContrastSliderChange'
                                    }
                                },
                                {
                                    xtype: 'label',
                                    localized: {
                                        text: 'label.designer.gammaLabel'
                                    },
                                    cls: 'image-outline-label',
                                    text: 'GAMMA',
                                    bind: {
                                        disabled: '{chkExtractOutline.checked}'
                                    }
                                },
                                {
                                    xtype: 'slider',
                                    cls: 'image-outline-sliders',
                                    itemId: 'gammaSlider',
                                    value: 0,
                                    decimalPrecision: 2,
                                    bind: {
                                        disabled: '{chkExtractOutline.checked}'
                                    },
                                    listeners: {
                                        change: 'onGammaSliderChange'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    localized: {
                                        boxLabel: 'label.designer.inverseLabel'
                                    },
                                    flex: 1,
                                    cls: 'image-outline-checkbox',
                                    itemId: 'chkInverse',
                                    boxLabel: 'INVERSE',
                                    listeners: {
                                        change: 'onInverseCheckboxChange'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'checkboxfield',
                    localized: {
                        boxLabel: 'label.designer.extractOutline'
                    },
                    reference: 'chkExtractOutline',
                    cls: 'image-outline-checkbox',
                    itemId: 'chkExtractOutline',
                    boxLabel: 'EXTRACT OUTLINE',
                    listeners: {
                        change: 'onExtractOutlineCheckboxChange'
                    }
                },
                {
                    xtype: 'panel',
                    margin: '0 0 0 28',
                    header: false,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            localized: {
                                text: 'label.designer.imageIntensity'
                            },
                            flex: 1,
                            cls: 'image-outline-label',
                            text: 'IMAGE DENSITY',
                            bind: {
                                disabled: '{!chkExtractOutline.checked}'
                            }
                        },
                        {
                            xtype: 'panel',
                            margin: '0 0 0 20',
                            header: false,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'slider',
                                    localized: {
                                        boxLabel: 'label.designer.imageIntensity'
                                    },
                                    flex: 1,
                                    cls: 'image-outline-sliders',
                                    itemId: 'imageIntensitySlider',
                                    labelPad: 15,
                                    maxValue: 255,
                                    bind: {
                                        disabled: '{!chkExtractOutline.checked}'
                                    },
                                    listeners: {
                                        change: 'onImageIntensitySliderChange'
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    header: false,
                                    layout: {
                                        type: 'vbox',
                                        align: 'center',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button.commandbutton',
                                            localized: {
                                                text: 'label.designer.extractAgain'
                                            },
                                            itemId: 'btnExtractAgainClient',
                                            margin: '0 10 0 0',
                                            text: 'EXTRACT AGAIN',
                                            bind: {
                                                disabled: '{!chkExtractOutline.checked}'
                                            },
                                            listeners: {
                                                click: 'onExtractAgainClientButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button.actionbutton',
                                            localized: {
                                                text: 'label.designer.extractAgain'
                                            },
                                            itemId: 'btnExtractAgain',
                                            margin: '0 10 0 0',
                                            text: 'EXTRACT AGAIN',
                                            bind: {
                                                disabled: '{!chkExtractOutline.checked}'
                                            },
                                            listeners: {
                                                click: 'onExtractAgainButtonClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

})
