/*
 * File: app/view/panel/MetalColorPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.panel.MetalColorPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panel.metalcolorpanel',

    requires: [
        'RolandKioskPrint.view.panel.MetalColorPanelViewModel',
        'RolandKioskPrint.view.panel.MetalColorPanelViewController',
        'Ext.form.field.Checkbox',
        'Ext.slider.Single'
    ],

    controller: 'panel.metalcolorpanel',
    viewModel: {
        type: 'panel.metalcolorpanel'
    },
    border: false,
    minHeight: 450,
    padding: 10,
    width: 200,
    header: false,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'checkboxfield',
            localized: {
                boxLabel: 'label.designer.fillSharpness'
            },
            reference: 'chkFillSharpness',
            itemId: 'chkFillSharpness',
            boxLabel: 'FILL SHARPNESS',
            checked: true,
            listeners: {
                change: 'onFillSharpnessCheckboxChange'
            }
        },
        {
            xtype: 'slider',
            itemId: 'sharpnessSlider',
            margin: '0 10 0 10',
            value: 85,
            increment: 15,
            minValue: 70,
            bind: {
                disabled: '{!chkFillSharpness.checked}'
            },
            listeners: {
                change: 'onSharpnessSliderChange'
            }
        },
        {
            xtype: 'checkboxfield',
            localized: {
                boxLabel: 'label.designer.drawOutline'
            },
            itemId: 'chkDrawOutline',
            margin: '10 0 0 0',
            boxLabel: 'DRAW OUTLINE',
            listeners: {
                change: 'onDrawOutlineCheckboxChange'
            }
        }
    ],
    listeners: {
        beforeshow: 'onPanelBeforeShow',
        hide: 'onPanelHide'
    }

})
