/*
 * File: app/view/panel/MiscPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.panel.MiscPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panel.miscpanel',

    requires: [
        'RolandKioskPrint.view.panel.MiscPanelViewModel',
        'RolandKioskPrint.view.panel.MiscPanelViewController',
        'RolandKioskPrint.view.button.PanelButton',
        'Ext.button.Button'
    ],

    config: {
        localized: {
            title: 'label.designer.copyDeleteTitle'
        }
    },

    controller: 'panel.miscpanel',
    viewModel: {
        type: 'panel.miscpanel'
    },
    cls: 'action-panel',
    width: 120,
    title: 'COPY / DELETE',
    titleAlign: 'center',

    layout: {
        type: 'hbox',
        pack: 'center'
    },
    items: [
        {
            xtype: 'button.panelbutton',
            cls: 'fa-clone first-column',
            itemId: 'btnCopy',
            listeners: {
                click: 'onCopyButtonClick'
            }
        },
        {
            xtype: 'button.panelbutton',
            cls: 'fa-trash',
            itemId: 'btnDelete',
            listeners: {
                click: 'onDeleteButtonClick'
            }
        }
    ]

})
