/*
 * File: app/view/panel/NavPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.panel.NavPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panel.navpanel',

    requires: [
        'RolandKioskPrint.view.panel.NavPanelViewModel',
        'RolandKioskPrint.view.panel.NavPanelViewController',
        'RolandKioskPrint.view.field.StepLabel',
        'RolandKioskPrint.view.panel.LangPanel',
        'Ext.panel.Panel',
        'Ext.form.Label'
    ],

    controller: 'panel.navpanel',
    viewModel: {
        type: 'panel.navpanel'
    },
    border: true,
    cls: 'nav-panel',
    height: 50,
    padding: 5,
    bodyBorder: true,
    bodyStyle: 'background-color: transparent
',
    frameHeader: false,
    header: false,

    layout: {
        type: 'hbox',
        align: 'stretch',
        pack: 'center'
    },
    dockedItems: [
        {
            xtype: 'panel',
            flex: 1,
            border: false,
            dock: 'left',
            width: 240,
            layout: 'table',
            bodyStyle: 'background-color: transparent
',
            header: false,
            items: [
                {
                    xtype: 'field.steplabel',
                    localized: {
                        text: 'label.nav.top'
                    },
                    cls: 'top-label',
                    itemId: 'lblTop',
                    width: 135,
                    text: 'TOP'
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            border: false,
            dock: 'right',
            width: 240,
            bodyStyle: 'background-color: transparent
',
            header: false,
            layout: {
                type: 'hbox',
                align: 'stretch',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'panel.langpanel',
                    clientSubView: true,
                    itemId: 'langPanel',
                    bodyStyle: 'background-color: transparent
',
                    flex: 1
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'panel',
            border: false,
            layout: 'table',
            bodyStyle: 'background-color: transparent
',
            frameHeader: false,
            items: [
                {
                    xtype: 'field.steplabel',
                    localized: {
                        text: 'label.nav.itemList'
                    },
                    cls: 'first-step',
                    itemId: 'lblItemList',
                    text: 'PRODUCT SELECTION'
                },
                {
                    xtype: 'field.steplabel',
                    localized: {
                        text: 'label.nav.check'
                    },
                    itemId: 'lblCheck',
                    text: 'CHECK'
                },
                {
                    xtype: 'field.steplabel',
                    localized: {
                        text: 'label.nav.edit'
                    },
                    itemId: 'lblEdit',
                    text: 'EDIT'
                },
                {
                    xtype: 'field.steplabel',
                    localized: {
                        text: 'label.nav.order'
                    },
                    cls: 'last-step',
                    itemId: 'lblOrder',
                    text: 'ORDER'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

})
