/*
 * File: app/view/button/CarouselButton.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.button.CarouselButton', {
    extend: 'Ext.button.Button',
    alias: 'widget.button.carouselbutton',

    requires: [
        'RolandKioskPrint.view.button.CarouselButtonViewModel'
    ],

    viewModel: {
        type: 'button.carouselbutton'
    },
    focusCls: 'carousel-button-focus',
    componentCls: 'carousel-button',
    height: 50,
    overCls: 'carousel-button-over',
    width: 50

})
