/*
 * File: app/view/Designer.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.Designer', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.designer',

    requires: [
        'RolandKioskPrint.view.DesignerViewModel',
        'RolandKioskPrint.view.DesignerViewController',
        'RolandKioskPrint.view.panel.NavPanel',
        'RolandKioskPrint.view.panel.ToolsPanel',
        'RolandKioskPrint.view.panel.CanvasPanel',
        'RolandKioskPrint.view.button.CommandButton',
        'RolandKioskPrint.view.button.DefaultCommandButton',
        'RolandKioskPrint.view.panel.UndoRedoPanel',
        'RolandKioskPrint.view.panel.FlipRotatePanel',
        'RolandKioskPrint.view.panel.GroupPanel',
        'RolandKioskPrint.view.panel.MiscPanel',
        'RolandKioskPrint.view.panel.AlignPanel',
        'RolandKioskPrint.view.panel.LayerPanel',
        'RolandKioskPrint.view.panel.GapAdjustmentPanel',
        'Ext.panel.Panel',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    controller: 'designer',
    viewModel: {
        type: 'designer'
    },
    layout: 'fit',
    bodyStyle: 'background-color: transparent
',
    header: false,
    title: 'My Panel',

    dockedItems: [
        {
            xtype: 'panel.navpanel',
            dock: 'top',
            itemId: 'navPanel'
        },
        {
            xtype: 'panel.toolspanel',
            cls: 'pd-toolspanel',
            dock: 'left',
            bodyStyle: 'background-color: transparent
'
        },
        {
            xtype: 'panel',
            border: false,
            cls: 'pd-action-panel-container',
            dock: 'right',
            itemId: 'actionPanelContainer',
            scrollable: 'vertical',
            bodyCls: 'action-panel-container',
            header: false,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel.undoredopanel',
                    itemId: 'undoRedoPanel'
                },
                {
                    xtype: 'panel.fliprotatepanel'
                },
                {
                    xtype: 'panel.grouppanel'
                },
                {
                    xtype: 'panel.miscpanel',
                    itemId: 'miscPanel'
                },
                {
                    xtype: 'panel.alignpanel'
                },
                {
                    xtype: 'panel.layerpanel'
                },
                {
                    xtype: 'panel.gapadjustmentpanel'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'panel',
            bodyStyle: 'background-color: transparent
',
            header: false,
            title: 'My Panel',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel.canvaspanel',
                    clientPanel: true,
                    itemId: 'canvasPanel',
                    bodyStyle: 'background-color: transparent
',
                    flex: 1
                },
                {
                    xtype: 'panel',
                    margin: '0 0 20 0',
                    bodyStyle: 'background-color: transparent
',
                    header: false,
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            localized: {
                                boxLabel: 'label.generic.guideline'
                            },
                            cls: 'chk-show-hide-guideline',
                            height: 32,
                            itemId: 'chkSmartGuide',
                            margin: '3 10 0 0',
                            minWidth: 120,
                            boxLabel: 'Guideline',
                            checked: true,
                            listeners: {
                                change: 'onSmartGuideChange'
                            }
                        },
                        {
                            xtype: 'button.commandbutton',
                            localized: {
                                text: 'label.button.back'
                            },
                            margin: '0 10 0 0',
                            text: 'BACK',
                            listeners: {
                                click: 'onBackButtonClick'
                            }
                        },
                        {
                            xtype: 'button.defaultcommandbutton',
                            localized: {
                                text: 'label.button.next'
                            },
                            margin: '0 10 0 0',
                            text: 'NEXT',
                            listeners: {
                                click: 'onNextButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforeshow: 'onMainViewBeforeShow',
        afterrender: 'onMainViewAfterRender',
        show: 'onMainViewShow',
        hide: 'onMainViewHide'
    }

})
