/*
 * File: app/view/OrderConfirmation.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.OrderConfirmation', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.orderconfirmation',

    requires: [
        'RolandKioskPrint.view.OrderConfirmationViewModel',
        'RolandKioskPrint.view.OrderConfirmationViewController',
        'RolandKioskPrint.view.button.CommandButton',
        'RolandKioskPrint.view.button.DefaultCommandButton',
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    controller: 'orderconfirmation',
    viewModel: {
        type: 'orderconfirmation'
    },
    bodyStyle: 'background-color: transparent
',
    header: false,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'panel',
            flex: 0.3,
            bodyStyle: 'background-color: transparent
',
            header: false
        },
        {
            xtype: 'label',
            localized: {
                text: 'label.designer.orderConfirmationTitle1'
            },
            flex: 0.1,
            cls: 'order-form-regular-labels',
            maxHeight: 20,
            text: 'Thank you very much for your order.'
        },
        {
            xtype: 'label',
            localized: {
                text: 'label.designer.orderConfirmationTitle2'
            },
            flex: 0.1,
            cls: 'order-form-regular-labels',
            text: 'Please wait until the STAFF comes.'
        },
        {
            xtype: 'label',
            localized: {
                text: 'label.designer.orderNumber'
            },
            flex: 0.1,
            cls: 'order-form-regular-labels',
            maxHeight: 30,
            text: 'Order Number'
        },
        {
            xtype: 'label',
            flex: 0.1,
            cls: [
                'order-form-regular-labels',
                'order-confirmation-form-large-labels'
            ],
            maxHeight: 30,
            bind: {
                text: '{orderNumberValue}'
            }
        },
        {
            xtype: 'panel',
            margin: '30 0 0 0',
            bodyStyle: 'background-color: transparent
',
            header: false,
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button.commandbutton',
                    localized: {
                        text: 'label.button.reCreate'
                    },
                    margin: '0 10 0 0',
                    text: 'RE-CREATE',
                    listeners: {
                        click: 'onRecreateButtonClick'
                    }
                },
                {
                    xtype: 'button.defaultcommandbutton',
                    localized: {
                        text: 'label.button.close'
                    },
                    itemId: 'btnClose',
                    text: 'CLOSE',
                    listeners: {
                        click: 'onCloseButtonClick'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 0.3,
            bodyStyle: 'background-color: transparent
',
            header: false
        }
    ],
    listeners: {
        show: 'onPanelShow',
        hide: 'onPanelHide'
    }

})
