/*
 * File: app/view/OrderConfirmationViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.OrderConfirmationViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.orderconfirmation',

    setCloseTimeOut: function() {
        var btnClose = this.getView().down('#btnClose')

        var controller = this


        var timeOutHandle = setTimeout(function(){
            controller.getViewModel().set('timeOutEnabled', false)
//Clear time out flaf
            btnClose.click()

        }, 120*1000)

        this.getViewModel().set('timeOutHandle', timeOutHandle)

        this.getViewModel().set('timeOutEnabled', true)

    },

    clearCloseTimeOut: function() {
        var timeOutEnabled = this.getViewModel().get('timeOutEnabled')

        if(timeOutEnabled){
            var timeOutHandle = this.getViewModel().get('timeOutHandle')

            clearTimeout(timeOutHandle)

            this.getViewModel().set('timeOutEnabled', false)

        }
    },

    onRecreateButtonClick: function(button, e, eOpts) {
        this.redirectTo('#client/editcontent', true)

    },

    onCloseButtonClick: function(button, e, eOpts) {
        this.fireEvent('orderConfirmationClosed')

        this.redirectTo('#client/top')

    },

    onPanelShow: function(component, eOpts) {
        this.setCloseTimeOut()

    },

    onPanelHide: function(component, eOpts) {
        this.clearCloseTimeOut()

    }

})

