/*
 * File: app/view/PMDMLDMain.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.PMDMLDMain', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pmdmldmain',

    requires: [
        'RolandKioskPrint.view.PMDMLDMainViewModel',
        'RolandKioskPrint.view.PMDMLDMainViewController',
        'RolandKioskPrint.view.panel.LangPanel',
        'RolandKioskPrint.view.button.GridPanelToolButton',
        'RolandKioskPrint.view.button.ActionButton',
        'Ext.form.Label',
        'Ext.form.field.File',
        'Ext.form.field.FileButton',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.filters.filter.List',
        'Ext.selection.RowModel',
        'Ext.grid.filters.Filters',
        'Ext.panel.Tool'
    ],

    config: {
        localized: {
            title: 'label.pmd_mld.pmdMldTitle'
        }
    },

    controller: 'pmdmldmain',
    viewModel: {
        type: 'pmdmldmain'
    },
    cls: 'pmd-mld-form',
    bodyStyle: 'background-color: rgb(206, 207, 209)
',
    title: 'cotodesign Template',

    layout: {
        type: 'vbox',
        align: 'stretch',
        pack: 'center'
    },
    dockedItems: [
        {
            xtype: 'panel',
            flex: 1,
            cls: 'separator-bar',
            dock: 'top',
            height: 10,
            header: false
        }
    ],
    items: [
        {
            xtype: 'panel',
            cls: 'pmd-mld-form-content-panel',
            flex: 1,
            header: false,
            title: 'My Panel',
            layout: {
                type: 'vbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'panel.langpanel'
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    header: false,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: '30 0 113 60',
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    cls: 'pmd-mld-grid-panel-header',
                                    height: 40,
                                    header: false,
                                    manageHeight: false,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            localized: {
                                                text: 'label.pmd_mld.pmList'
                                            },
                                            cls: 'header-text',
                                            text: 'PRODUCT MODEL LIST'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            cls: 'grid-panel-tools',
                                            header: false,
                                            layout: {
                                                type: 'hbox',
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.newPM'
                                                    },
                                                    cls: 'fa-file-o',
                                                    margin: '0 6 0 0',
                                                    tooltip: 'New Product Model',
                                                    tooltipType: 'title',
                                                    listeners: {
                                                        click: 'onNewProductModelButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.editPM'
                                                    },
                                                    cls: 'fa-pencil',
                                                    margin: '0 6 0 0',
                                                    tooltip: 'Edit Product Model',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!productModelList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onEditProductModelButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'filefield',
                                                    height: 24,
                                                    itemId: 'flfImportProductModel',
                                                    margin: '0 6 0 0',
                                                    width: 24,
                                                    hideLabel: true,
                                                    buttonOnly: true,
                                                    buttonText: null,
                                                    buttonConfig: {
                                                        xtype: 'filebutton',
                                                        localized: {
                                                            tooltip: 'label.pmd_mld.importPM'
                                                        },
                                                        cls: 'pmd-mld-grid-panel-tool-button fa-download',
                                                        tooltip: 'Import Product Model (SVG)',
                                                        tooltipType: 'title'
                                                    },
                                                    listeners: {
                                                        change: 'onImportProductModel'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.previewPM'
                                                    },
                                                    cls: 'fa-search',
                                                    margin: '0 6 0 0',
                                                    tooltip: 'Preview Product Model',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!productModelList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onPreviewProductModelButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.deletePM'
                                                    },
                                                    cls: 'fa-trash',
                                                    tooltip: 'Delete Product Model',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!productModelList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onDeleteProductModelButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'filefield',
                                                    height: 24,
                                                    itemId: 'flfUploadProductModel',
                                                    margin: '0 6 0 0',
                                                    width: 24,
                                                    hideLabel: true,
                                                    buttonOnly: true,
                                                    buttonText: null,
                                                    buttonConfig: {
                                                        xtype: 'filebutton',
                                                        localized: {
                                                            tooltip: 'label.pmd_mld.uploadPM'
                                                        },
                                                        cls: 'pmd-mld-grid-panel-tool-button fa-folder-open',
                                                        tooltip: 'Upload Product Model',
                                                        tooltipType: 'title'
                                                    },
                                                    listeners: {
                                                        change: 'onUploadProductModel'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.savePM'
                                                    },
                                                    cls: 'fa-save',
                                                    tooltip: 'Save Product Model',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!productModelList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onSaveProductModelButtonClick'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    reference: 'productModelList',
                                    cls: [
                                        'pmd-mld-grid-panel',
                                        'noborder-top'
                                    ],
                                    flex: 1,
                                    id: 'productModelListMain',
                                    itemId: 'productModelList',
                                    header: {
                                        xtype: 'panel',
                                        header: false,
                                        layout: {
                                            type: 'hbox',
                                            pack: 'end'
                                        },
                                        cls: 'pmd-mld-filter-panel',
                                        height: 35,
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                style: 'width: 0
 height: 0; visibility: hidden',
                                                id: 'username'
                                            },
                                            {
                                                xtype: 'textfield',
                                                emptyText: 'Filter name...',
                                                localized: {
                                                    emptyText: 'label.pmd_mld.filterName'
                                                },
                                                width: 250,
                                                fieldCls: 'pmd-mld-search-field',
                                                cls: 'pmd-mld-search-icon',
                                                hideLabel: true,
                                                triggers: {
                                                    search: {
                                                        
                                                    }
                                                },
                                                listeners: {
                                                    change: 'onSearchTextfieldChange'
                                                }
                                            }
                                        ]
                                    },
                                    enableColumnHide: false,
                                    enableColumnMove: false,
                                    enableColumnResize: false,
                                    sortableColumns: false,
                                    store: 'ProductModels',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var connectedLayouts = record.get('connectedLayouts')

                                                if (!connectedLayouts || connectedLayouts.length === 0) {
                                                    metaData.tdStyle = 'color: red'

                                                }
                                                return value

                                            },
                                            localized: {
                                                text: 'label.generic.name'
                                            },
                                            flex: 0.56,
                                            dataIndex: 'modelName',
                                            text: 'NAME'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var applied = ''

                                                var data = record.data


                                                if (RolandKioskPrint.app.isColorPrintModel(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-color"></div>'

                                                }

                                                if (RolandKioskPrint.app.isFoilPrintModel(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-foil"></div>'

                                                }

                                                if (RolandKioskPrint.app.isMetalPrintModel(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-metal"></div>'

                                                }

                                                if (RolandKioskPrint.app.isCutPrintModel(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-cut"></div>'

                                                }

                                                return applied

                                            },
                                            localized: {
                                                text: 'label.generic.printType'
                                            },
                                            cls: 'print-type-column-header',
                                            flex: 0.24,
                                            dataIndex: 'printType',
                                            tdCls: 'pmd-mld-grid-panel-print-type-cell',
                                            text: 'PRINT TYPE',
                                            filter: {
                                                type: 'list'
                                            },
                                            listeners: {
                                                headertriggerclick: 'onProductModelListHeaderTriggerClick'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var applied = ''

                                                var data = record.data


                                                if (data.primer == 'on') {
                                                    applied += '<div class="pmd-mld-grid-special-effects-icon img-special-effects-primer"></div>'

                                                }

                                                if (data.white == 'on') {
                                                    applied += '<div class="pmd-mld-grid-special-effects-icon img-special-effects-white"></div>'

                                                }

                                                if (data.varnish == 'on') {
                                                    if (data.varnishType == RolandKioskPrint.app.constants.GLOSS_VARNISH) {
                                                        applied += '<div class="pmd-mld-grid-special-effects-icon img-special-effects-gloss"></div>'

                                                    } else if (data.varnishType == RolandKioskPrint.app.constants.MATTE_VARNISH) {
                                                        applied += '<div class="pmd-mld-grid-special-effects-icon img-special-effects-matte"></div>'

                                                    }
                                                }

                                                if (data.backPrint == 'on') {
                                                    applied += '<div class="pmd-mld-grid-special-effects-icon img-special-effects-reverse-print"></div>'

                                                }

                                                return applied

                                            },
                                            localized: {
                                                text: 'label.generic.specialEffect'
                                            },
                                            flex: 0.2,
                                            dataIndex: 'modelName',
                                            tdCls: 'pmd-mld-grid-panel-special-effects-cell',
                                            text: 'SPECIAL EFFECT'
                                        }
                                    ],
                                    selModel: {
                                        selType: 'rowmodel',
                                        mode: 'SINGLE'
                                    },
                                    listeners: {
                                        selectionchange: 'onProductModelListSelectionChange',
                                        itemdblclick: 'onProductModelListItemDblClick',
                                        beforedeselect: 'onProductModelListBeforeDeselect',
                                        afterrender: 'onProductModelListAfterRender'
                                    },
                                    plugins: [
                                        {
                                            ptype: 'gridfilters'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            width: 64,
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'fa fa-chain',
                                    height: 64,
                                    id: 'chain-icon',
                                    width: 64
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            margin: '30 60 60 0',
                            header: false,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    cls: 'pmd-mld-grid-panel-header',
                                    height: 40,
                                    header: false,
                                    manageHeight: false,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            localized: {
                                                text: 'label.pmd_mld.mlList'
                                            },
                                            cls: 'header-text',
                                            text: 'MODEL LAYOUT LIST'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            cls: 'grid-panel-tools',
                                            header: false,
                                            layout: {
                                                type: 'hbox',
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.newML'
                                                    },
                                                    cls: 'fa-file-o',
                                                    margin: '0 6 0 0',
                                                    tooltip: 'New Model Layout',
                                                    tooltipType: 'title',
                                                    listeners: {
                                                        click: 'onNewModelLayoutButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.editML'
                                                    },
                                                    cls: 'fa-pencil',
                                                    margin: '0 6 0 0',
                                                    tooltip: 'Edit Model Layout',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!modelLayoutList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onEditModelLayoutButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'filefield',
                                                    height: 24,
                                                    margin: '0 6 0 0',
                                                    width: 24,
                                                    hideLabel: true,
                                                    buttonOnly: true,
                                                    buttonText: null,
                                                    buttonConfig: {
                                                        xtype: 'filebutton',
                                                        localized: {
                                                            tooltip: 'label.pmd_mld.importML'
                                                        },
                                                        cls: 'pmd-mld-grid-panel-tool-button fa-download',
                                                        tooltip: 'Import Model Layout (SVG)',
                                                        tooltipType: 'title'
                                                    },
                                                    listeners: {
                                                        change: 'onImportModelLayout'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.previewML'
                                                    },
                                                    cls: 'fa-search',
                                                    margin: '0 6 0 0',
                                                    tooltip: 'Preview Model Layout',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!modelLayoutList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onPreviewModelLayoutButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.deleteML'
                                                    },
                                                    cls: 'fa-trash',
                                                    tooltip: 'Delete Model Layout',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!modelLayoutList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onDeleteModelLayoutButtonClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'filefield',
                                                    height: 24,
                                                    itemId: 'flfUploadModelLayout',
                                                    margin: '0 6 0 0',
                                                    width: 24,
                                                    hideLabel: true,
                                                    buttonOnly: true,
                                                    buttonText: null,
                                                    buttonConfig: {
                                                        xtype: 'filebutton',
                                                        localized: {
                                                            tooltip: 'label.pmd_mld.uploadML'
                                                        },
                                                        cls: 'pmd-mld-grid-panel-tool-button fa-folder-open',
                                                        tooltip: 'Upload Product Model',
                                                        tooltipType: 'title'
                                                    },
                                                    listeners: {
                                                        change: 'onUploadModelLayout'
                                                    }
                                                },
                                                {
                                                    xtype: 'button.gridpaneltoolbutton',
                                                    localized: {
                                                        tooltip: 'label.pmd_mld.saveML'
                                                    },
                                                    cls: 'fa-save',
                                                    tooltip: 'Save Product Model',
                                                    tooltipType: 'title',
                                                    bind: {
                                                        disabled: '{!modelLayoutList.selection}'
                                                    },
                                                    listeners: {
                                                        click: 'onSaveModelLayoutButtonClick'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    reference: 'modelLayoutList',
                                    cls: [
                                        'pmd-mld-grid-panel',
                                        'noborder-top'
                                    ],
                                    flex: 1,
                                    id: 'modelLayoutListMain',
                                    itemId: 'modelLayoutList',
                                    margin: '0 0 20 0',
                                    header: false,
                                    enableColumnHide: false,
                                    enableColumnMove: false,
                                    enableColumnResize: false,
                                    sortableColumns: false,
                                    store: 'ModelLayouts',
                                    columns: [
                                        {
                                            xtype: 'checkcolumn',
                                            localized: {
                                                text: 'label.generic.connect'
                                            },
                                            listeners: {
                                                checkchange: function(cell, rowIndex, checked, record, e, eOpts) {
                                                    var mainView = this.up('#pmdMldMainView')

                                            
                                                    var layoutRecords = mainView.getController().getConnectedModelLayoutRecords()

                                                    var modelLayoutList = this.getView()

                                                    var store = modelLayoutList.getStore()

                                            
                                                    var hasDefaultLayout = false

                                                    var potentialLayout

                                            
                                                    layoutRecords.forEach(function(layout) {
                                                        var isConnected = layout.get('isConnected')

                                                        var isDefault = layout.get('isDefault')

                                            
                                                        if (isDefault) {
                                                            hasDefaultLayout = true

                                                        }
                                            
                                                        if (!potentialLayout && isConnected && store.indexOf(layout) !== rowIndex) {
                                                            potentialLayout = layout

                                                        }
                                                    })

                                            
                                                    if (checked) {
                                                        modelLayoutList.select(rowIndex)

                                                        if (!hasDefaultLayout) {
                                                            record.set('isDefault', true)

                                                        }
                                                    } else {
                                                        modelLayoutList.deselect(rowIndex)

                                                        record.set('isDefault', false)

                                            
                                                        if (potentialLayout) {
                                                            modelLayoutList.select(store.indexOf(potentialLayout))

                                            
                                                            if (!hasDefaultLayout) {
                                                                potentialLayout.set('isDefault', true)

                                                            }
                                                        }
                                                    }
                                            
                                                    modelLayoutList.refresh()

                                                    mainView.getController().setConnectionsDirty(true)

                                                }
                                            },
                                            width: 100,
                                            align: 'center',
                                            dataIndex: 'isConnected',
                                            text: 'CONNECT'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var render = []


                                                render.push('<input type="radio" name="defaultRadio" class="x-grid-radiocolumn" ')

                                                if (value) {
                                                    render.push('checked="checked" ')

                                                }
                                                render.push('onchange="Ext.StoreManager.lookup(\'' + store.storeId + '\').each(function(record, idx) {')

                                                    render.push('if (idx == ' + rowIndex + ') {')

                                                        render.push('record.set(\'isDefault\', true)
');
                                                        render.push('record.set(\'isConnected\', true)
');
                                                    render.push('} else {')

                                                        render.push('record.set(\'isDefault\', false)
');
                                                    render.push('}')

                                                render.push('})
');
                                                render.push('var mainView = Ext.getCmp(\'pmdMldMainView\')
');
                                                render.push('mainView.getController().setConnectionsDirty(true)
"');
                                                render.push('>')


                                                //console.log(render.join(''))

                                                return render.join('')

                                            },
                                            localized: {
                                                text: 'label.generic.default'
                                            },
                                            cls: 'pmd-mld-grid-panel-default-column',
                                            width: 110,
                                            align: 'center',
                                            dataIndex: 'isDefault',
                                            text: 'DEFAULT'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            localized: {
                                                text: 'label.generic.name'
                                            },
                                            flex: 0.65,
                                            dataIndex: 'layoutName',
                                            text: 'NAME'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                var applied = ''

                                                var data = record.data


                                                if (RolandKioskPrint.app.isColorPrintLayout(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-color"></div>'

                                                } else if (RolandKioskPrint.app.isFoilPrintLayout(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-foil"></div>'

                                                } else if (RolandKioskPrint.app.isMetalPrintLayout(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-metal"></div>'

                                                } else if (RolandKioskPrint.app.isCutPrintLayout(data)) {
                                                    applied += '<div class="pmd-mld-grid-print-type-icon img-print-type-cut"></div>'

                                                }

                                                return applied

                                            },
                                            localized: {
                                                text: 'label.generic.printType'
                                            },
                                            cls: 'print-type-column-header',
                                            flex: 0.35,
                                            dataIndex: 'printType',
                                            tdCls: 'pmd-mld-grid-panel-print-type-cell',
                                            text: 'PRINT TYPE',
                                            filter: {
                                                type: 'list'
                                            },
                                            listeners: {
                                                headertriggerclick: 'onModelLayoutListHeaderTriggerClick'
                                            }
                                        }
                                    ],
                                    selModel: {
                                        selType: 'rowmodel',
                                        mode: 'SINGLE'
                                    },
                                    listeners: {
                                        itemdblclick: 'onModelLayoutListItemDblClick',
                                        afterrender: 'onModelLayoutListAfterRender'
                                    },
                                    plugins: [
                                        {
                                            ptype: 'gridfilters'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    header: false,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'button.actionbutton',
                                            localized: {
                                                text: 'label.button.save'
                                            },
                                            text: 'SAVE',
                                            bind: {
                                                disabled: '{saveDisabled}'
                                            },
                                            listeners: {
                                                click: 'onSaveConnectionsButtonClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        show: 'onMainViewShow',
        hide: 'onMainViewHide'
    },
    tools: [
        {
            xtype: 'tool',
            callback: 'showChangePasswordScreen',
            cls: 'pmd-mld-change-password-tool',
            iconCls: 'fa fa-key'
        },
        {
            xtype: 'tool',
            callback: 'showHelp',
            cls: 'pmd-mld-help-tool',
            type: 'help'
        }
    ]

})
