/*
 * File: app/view/ProductModelDesignerImageOutline.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.ProductModelDesignerImageOutline', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.productmodeldesignerimageoutline',

    requires: [
        'RolandKioskPrint.view.ProductModelDesignerImageOutlineViewModel',
        'RolandKioskPrint.view.ProductModelDesignerImageOutlineViewController',
        'RolandKioskPrint.view.panel.ImageOutlinePanel',
        'RolandKioskPrint.view.button.ActionButton',
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    config: {
        localized: {
            title: 'label.designer.pmdImageAdjustTitle'
        }
    },

    controller: 'productmodeldesignerimageoutline',
    viewModel: {
        type: 'productmodeldesignerimageoutline'
    },
    modal: true,
    cls: 'pmd-mld-form',
    floating: true,
    height: 565,
    width: 800,
    bodyStyle: 'background-color: rgb(206, 207, 209)
',
    title: 'EDIT IMAGE',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'panel',
            flex: 1,
            cls: 'separator-bar',
            dock: 'top',
            height: 8,
            header: false,
            title: 'My Panel'
        }
    ],
    items: [
        {
            xtype: 'panel',
            flex: 1,
            cls: 'pmd-mld-form-content-panel',
            header: false,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'label',
                    localized: {
                        text: 'label.designer.imageOutlineTitle'
                    },
                    cls: 'product-image-adjust-top-label',
                    height: 30,
                    text: 'Please adjust image threshold'
                },
                {
                    xtype: 'panel.imageoutlinepanel',
                    itemId: 'imageOutlinePanel',
                    margin: '10 0 0 0',
                    flex: 1
                },
                {
                    xtype: 'panel',
                    flex: 0.1,
                    margin: '10 0 10 0',
                    maxHeight: 30,
                    header: false,
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button.actionbutton',
                            localized: {
                                text: 'label.designer.revertChanges'
                            },
                            itemId: 'btnRevert',
                            margin: '0 0 0 50',
                            minWidth: 100,
                            width: ' ',
                            text: 'Revert Changes',
                            listeners: {
                                click: 'onRevertButtonClick'
                            }
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            header: false
                        },
                        {
                            xtype: 'button.actionbutton',
                            localized: {
                                text: 'label.button.cancel'
                            },
                            margin: '0 10 0 0',
                            width: 100,
                            text: 'CANCEL',
                            listeners: {
                                click: 'onCancelButtonClick'
                            }
                        },
                        {
                            xtype: 'button.actionbutton',
                            localized: {
                                text: 'label.button.ok'
                            },
                            margin: '0 10 0 0',
                            width: 100,
                            text: 'OK',
                            listeners: {
                                click: 'onOKButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforeshow: 'onPanelBeforeShow'
    }

})
