/*
 * File: app/view/ProductModelDesignerVarnishFirstUseViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.ProductModelDesignerVarnishFirstUseViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.productmodeldesignervarnishfirstuse',

    getImageUrl: function() {
        // The first use image is different for different locales.
        // Pick the right image based on the cotodesign UI locale.

        var curPrefLang = RolandKioskPrint.app.getPrefLanguage()


        var imgUrl = 'resources/images/lang-specific/' + curPrefLang + '/VarnishFirstUse.png'


        return imgUrl

    },

    onCloseButtonClick: function(button, e, eOpts) {
        RolandKioskPrint.app.destroyModalView(this.getView())

    },

    onPanelAfterRender: function(component, eOpts) {
        var imgFirstUse = this.getView().down('#imgFirstUse')

        var url = "url('" + this.getImageUrl()+ "')"


        imgFirstUse.setStyle({
            backgroundImage: url,
            backgroundRepeat: 'no-repeat',
            backgroundSize: 'contain',
            backgroundPosition: 'center center'
        })

    }

})

