/*
 * File: app/store/Shapes.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.store.Shapes', {
    extend: 'Ext.data.Store',

    requires: [
        'RolandKioskPrint.model.Shape'
    ],

    constructor: function(cfg) {
        var me = this

        cfg = cfg || {}

        me.callParent([Ext.apply({
            storeId: 'Shapes',
            model: 'RolandKioskPrint.model.Shape',
            data: [
                {
                    shapeType: 1,
                    iconClass: 'icomoon4 icon-rectangle'
                },
                {
                    shapeType: 2,
                    iconClass: 'icomoon4 icon-circle'
                },
                {
                    shapeType: 3,
                    iconClass: 'icomoon4 icon-triangle'
                },
                {
                    shapeType: 4,
                    iconClass: 'icomoon4 icon-pentagon'
                },
                {
                    shapeType: 5,
                    iconClass: 'icomoon4 icon-hexagon'
                },
                {
                    shapeType: 6,
                    iconClass: 'icomoon4 icon-heart'
                },
                {
                    shapeType: 7,
                    iconClass: 'icomoon4 icon-rounded-rectangle'
                },
                {
                    shapeType: 8,
                    iconClass: 'icomoon4 icon-speech-bubble'
                },
                {
                    shapeType: 9,
                    iconClass: 'icomoon4 icon-trapezium'
                },
                {
                    shapeType: 10,
                    iconClass: 'icomoon4 icon-star'
                },
                {
                    shapeType: 11,
                    iconClass: 'icomoon4 icon-diamond'
                }
            ]
        }, cfg)])

    }
})
