/*
 * File: app/view/MyModelsViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ViewOverviewExtJS.view.MyModelsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.mymodels',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        myModels: {
            model: 'ViewOverviewExtJS.model.MyModel',
            data: [
                {
                    id: 1,
                    myField: 'sed'
                },
                {
                    id: 2,
                    myField: 'consequuntur'
                },
                {
                    id: 3,
                    myField: 'iusto'
                },
                {
                    id: 4,
                    myField: 'architecto'
                },
                {
                    id: 5,
                    myField: 'laborum'
                },
                {
                    id: 6,
                    myField: 'et'
                },
                {
                    id: 7,
                    myField: 'nam'
                },
                {
                    id: 8,
                    myField: 'sunt'
                },
                {
                    id: 9,
                    myField: 'quae'
                },
                {
                    id: 10,
                    myField: 'rerum'
                },
                {
                    id: 11,
                    myField: 'molestiae'
                },
                {
                    id: 12,
                    myField: 'voluptatem'
                },
                {
                    id: 13,
                    myField: 'ipsam'
                },
                {
                    id: 14,
                    myField: 'minus'
                },
                {
                    id: 15,
                    myField: 'accusantium'
                },
                {
                    id: 16,
                    myField: 'qui'
                },
                {
                    id: 17,
                    myField: 'vitae'
                },
                {
                    id: 18,
                    myField: 'occaecati'
                },
                {
                    id: 19,
                    myField: 'occaecati'
                },
                {
                    id: 20,
                    myField: 'molestiae'
                },
                {
                    id: 21,
                    myField: 'explicabo'
                },
                {
                    id: 22,
                    myField: 'ea'
                },
                {
                    id: 23,
                    myField: 'aut'
                },
                {
                    id: 24,
                    myField: 'voluptates'
                },
                {
                    id: 25,
                    myField: 'dolores'
                },
                {
                    id: 26,
                    myField: 'ipsum'
                },
                {
                    id: 27,
                    myField: 'dolore'
                },
                {
                    id: 28,
                    myField: 'omnis'
                },
                {
                    id: 29,
                    myField: 'pariatur'
                },
                {
                    id: 30,
                    myField: 'perferendis'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});