/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cotoplatform.view.MyPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mypanel',

    requires: [
        'cotoplatform.view.MyPanelViewModel',
        'Ext.tab.Panel',
        'Ext.grid.Grid',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Text'
    ],

    viewModel: {
        type: 'mypanel'
    },
    title: 'My Panel',

    items: [
        {
            xtype: 'tabpanel',
            items: [
                {
                    xtype: 'container',
                    title: 'Tab 1'
                },
                {
                    xtype: 'container',
                    title: 'Tab 2'
                },
                {
                    xtype: 'container',
                    title: 'Tab 3'
                },
                {
                    xtype: 'container',
                    title: 'Tab 3'
                },
                {
                    xtype: 'container',
                    title: 'Tab 3'
                }
            ]
        },
        {
            xtype: 'grid',
            height: 238,
            width: '100%',
            grouped: true,
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 70,
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    width: 89,
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    width: 89,
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    text: 'MyColumn1'
                },
                {
                    xtype: 'gridcolumn',
                    width: 80,
                    text: 'MyColumn2'
                },
                {
                    xtype: 'textcolumn',
                    width: 80,
                    text: 'MyTextColumn'
                }
            ]
        }
    ]

});