/*
 * File: app/view/field/ColorPicker.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RolandKioskPrint.view.field.ColorPicker', {
    extend: 'Ext.form.field.Text',
    alias: 'widget.field.colorpicker',

    requires: [
        'RolandKioskPrint.view.field.ColorPickerViewModel',
        'Ext.form.trigger.Trigger'
    ],

    viewModel: {
        type: 'field.colorpicker'
    },
    width: 210,
    fieldLabel: 'Label',
    readOnly: false,
    editable: false,

    triggers: {
        mytrigger: {
            handler: function(field, trigger, e) {
                if (!this.menu) {
                    this.menu = Ext.create('Ext.menu.ColorPicker', {
                        value: '000000'
                    })


                    this.menu.on('select', this.onColorChange, this)

                }

                if (this.value) {
                    var value = this.value.replace('#', '')
 // Remove the leading '#'
                    this.menu.value = value

                    this.menu.picker.value = value

                }

                this.menu.showAt(e.getXY())

            }
        }
    },

    setValue: function(value) {
        this.inputEl.setStyle({
            backgroundColor: value
        })


        this.value = value

    },

    getValue: function() {
        return this.value

    },

    onColorChange: function(feild, color, opts) {
        var oldValue = this.value

        this.value = '#' + color

        this.inputEl.setStyle({
            backgroundColor: this.value
        })


        this.fireEvent('change', this, this.value, oldValue)

    }

})
